services:
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: kafka
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    networks:
      - lakehouse-network


  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    hostname: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8083:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_UI_SERVER_PORT: 8080
    networks:
      - lakehouse-network

#
#  namenode:
#    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
#    hostname: namenode
#    container_name: namenode
#    ports:
#      - "9870:9870"
#      - "9000:9000"
#    environment:
#      CLUSTER_NAME: hadoop-cluster
#      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
#      CORE_CONF_hadoop_http_staticuser_user: root
#      HDFS_CONF_dfs_webhdfs_enabled: 'true'
#      HDFS_CONF_dfs_permissions_enabled: 'false'
#      HDFS_CONF_dfs_replication: 1
#    volumes:
#      - hadoop_namenode:/hadoop/dfs/name
#    networks:
#      - lakehouse-network

#
#  datanode:
#    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
#    hostname: datanode
#    container_name: datanode
#    depends_on:
#      - namenode
#    ports:
#      - "9864:9864"
#    environment:
#      SERVICE_PRECONDITION: "namenode:9870"
#      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
#      HDFS_CONF_dfs_replication: 1
#    volumes:
#      - hadoop_datanode:/hadoop/dfs/data
#    networks:
#      - lakehouse-network


  spark-master:
    image: apache/spark:3.5.0
    container_name: spark-master
    hostname: spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
    environment:
      SPARK_MASTER_PORT: 7077
      SPARK_MASTER_WEBUI_PORT: 8080
      SPARK_HADOOP_FS_DEFAULTFS: s3a://mybucket
    networks:
      - lakehouse-network
    volumes:
      - ./spark_job:/opt/spark-jobs


  worker01:
    image: apache/spark:3.5.0
    container_name: worker01
    hostname: worker01
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      SPARK_WORKER_MEMORY: 2G
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_HADOOP_FS_DEFAULTFS: hdfs://namenode:9000
    networks:
      - lakehouse-network


  worker02:
    image: apache/spark:3.5.0
    container_name: worker02
    hostname: worker02
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      SPARK_WORKER_MEMORY: 2G
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_HADOOP_FS_DEFAULTFS: hdfs://namenode:9000
    networks:
      - lakehouse-network


  clickhouse:
    image: yandex/clickhouse-server:21.2.5
    container_name: clickhouse
    hostname: clickhouse
    ports:
      - "8123:8123"
      - "9002:9000"
      - "9003:9001"
    environment:
      CLICKHOUSE_DB: ecommerce
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: password
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - lakehouse-network


  prometheus:
    image: prom/prometheus:v2.50.0
    container_name: prometheus
    hostname: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - lakehouse-network


  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana
    hostname: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: password
      GF_INSTALL_PLUGINS: ''
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    networks:
      - lakehouse-network


  node-exporter:
    image: prom/node-exporter:v1.7.0
    container_name: node-exporter
    hostname: node-exporter
    ports:
      - "9100:9100"
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - lakehouse-network


  kafka-exporter:
    image: danielqsj/kafka-exporter:v1.5.0
    container_name: kafka-exporter
    hostname: kafka-exporter
    depends_on:
      - kafka
    ports:
      - "9308:9308"
    command:
      - '--kafka.server=kafka:29092'
    networks:
      - lakehouse-network


  clickhouse-exporter:
    image: f1yegor/clickhouse-exporter
    container_name: clickhouse-exporter
    hostname: clickhouse-exporter
    ports:
      - "9116:9116"
    environment:
      CLICKHOUSE_EXPORTER_CLICKHOUSE_ADDR: http://clickhouse:8123
      CLICKHOUSE_EXPORTER_LISTEN_ADDR: ":9116"
    networks:
      - lakehouse-network


  # ============================= AIRFLOW =============================
  airflow:
    image: apache/airflow:latest
    container_name: airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=True
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
      - AIRFLOW__WEBSERVER__WEB_SERVER_PORT=8085
    ports:
      - "8085:8085"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
    command: standalone
    restart: always
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: minio
    hostname: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server /data/minio --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - lakehouse-network

  mc:
    image: minio/mc:latest
    container_name: mc
    hostname: mc
    depends_on:
      - minio
    entrypoint: >
      sh -c "
      sleep 10 &&
      mc alias set local http://minio:9000 admin password &&
      mc mb local/mybucket &&
      mc policy set public local/mybucket
      "
    networks:
      - lakehouse-network


networks:
  lakehouse-network:
    driver: bridge

volumes:
#  hadoop_namenode:
#  hadoop_datanode:
  clickhouse_data:
  minio_data:
  prometheus_data:
  grafana_data:


