apiVersion: v1
kind: Secret
metadata:
  name: debezium-secret
  namespace: kafka
type: Opaque
stringData:
  postgres-host: "database-postgresql.database.svc.cluster.local"
  postgres-port: "5432"
  postgres-user: "debezium_user"
  postgres-password: "debezium_password"
  postgres-database: "ecommerce_db"

  kafka-bootstrap-servers: "kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"

