apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-ui.service.name" . }}
  labels:
    {{ include "kafka.labels" . | nindent 4 }}
    component: kafka-ui
spec:
  type: {{ .Values.kafkaUi.service.type }}
  ports:
  - name: http
    port: {{ .Values.kafkaUi.service.port }}
    targetPort: {{ .Values.kafkaUi.service.port }}
  selector:
    {{ include "kafka.selectorLabels" . | nindent 4 }}
    component: kafka-ui