apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml -o ./kompose/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: clickhouse-exporter
  name: clickhouse-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: clickhouse-exporter
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml -o ./kompose/
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: clickhouse-exporter
    spec:
      containers:
        - env:
            - name: CLICKHOUSE_EXPORTER_CLICKHOUSE_ADDR
              value: http://clickhouse:8123
            - name: CLICKHOUSE_EXPORTER_LISTEN_ADDR
              value: :9116
          image: f1yegor/clickhouse-exporter
          name: clickhouse-exporter
          ports:
            - containerPort: 9116
              protocol: TCP
      hostname: clickhouse-exporter
      restartPolicy: Always
