apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml -o ./kompose/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: clickhouse
  name: clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: clickhouse
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml -o ./kompose/
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: clickhouse
    spec:
      containers:
        - env:
            - name: CLICKHOUSE_DB
              value: ecommerce
            - name: CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT
              value: "1"
            - name: CLICKHOUSE_PASSWORD
              value: password
            - name: CLICKHOUSE_USER
              value: admin
          image: yandex/clickhouse-server:21.2.5
#          livenessProbe:
#            exec:
#              command:
#                - echo 'SELECT 1' | clickhouse-client --host localhost --port 9000 --user=admin --password=password || exit 1
#            failureThreshold: 3
#            initialDelaySeconds: 15
#            periodSeconds: 10
#            timeoutSeconds: 5
          name: clickhouse
          ports:
            - containerPort: 8123
              protocol: TCP
            - containerPort: 9001
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/clickhouse
              name: clickhouse-data
      hostname: clickhouse
      restartPolicy: Always
      volumes:
        - name: clickhouse-data
          persistentVolumeClaim:
            claimName: clickhouse-data
