apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml -o ./kompose/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: namenode
  name: namenode
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: namenode
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml -o ./kompose/
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: namenode
    spec:
      containers:
        - env:
            - name: CLUSTER_NAME
              value: hadoop-cluster
            - name: CORE_CONF_fs_defaultFS
              value: hdfs://namenode:9000
            - name: CORE_CONF_hadoop_http_staticuser_user
              value: root
            - name: HDFS_CONF_dfs_permissions_enabled
              value: "false"
            - name: HDFS_CONF_dfs_replication
              value: "1"
            - name: HDFS_CONF_dfs_webhdfs_enabled
              value: "true"
          image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
          name: namenode
          ports:
            - containerPort: 9870
              protocol: TCP
            - containerPort: 9000
              protocol: TCP
          volumeMounts:
            - mountPath: /hadoop/dfs/name
              name: hadoop-namenode
      hostname: namenode
      restartPolicy: Always
      volumes:
        - name: hadoop-namenode
          persistentVolumeClaim:
            claimName: hadoop-namenode
