apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml -o ./kompose/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: node-exporter
  name: node-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: node-exporter
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml -o ./kompose/
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: node-exporter
    spec:
      containers:
        - args:
            - --path.procfs=/host/proc
            - --path.rootfs=/rootfs
            - --path.sysfs=/host/sys
            - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($()|/)
          image: prom/node-exporter:v1.7.0
          name: node-exporter
          ports:
            - containerPort: 9100
              protocol: TCP
          volumeMounts:
            - mountPath: /host/proc
              name: node-exporter-claim0
              readOnly: true
            - mountPath: /host/sys
              name: node-exporter-claim1
              readOnly: true
      hostname: node-exporter
      restartPolicy: Always
      volumes:
        - name: node-exporter-claim0
          persistentVolumeClaim:
            claimName: node-exporter-claim0
            readOnly: true
        - name: node-exporter-claim1
          persistentVolumeClaim:
            claimName: node-exporter-claim1
            readOnly: true
