apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml -o ./kompose/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: worker02
  name: worker02
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: worker02
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml -o ./kompose/
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: worker02
    spec:
      containers:
        - args:
            - /opt/spark/bin/spark-class
            - org.apache.spark.deploy.worker.Worker
            - spark://spark-master:7077
          env:
            - name: SPARK_HADOOP_FS_DEFAULTFS
              value: hdfs://namenode:9000
            - name: SPARK_WORKER_CORES
              value: "2"
            - name: SPARK_WORKER_MEMORY
              value: 2G
            - name: SPARK_WORKER_WEBUI_PORT
              value: "8081"
          image: apache/spark:3.5.0
          name: worker02
          ports:
            - containerPort: 8081
              protocol: TCP
      hostname: worker02
      restartPolicy: Always
