apiVersion: v1
kind: ConfigMap
metadata:
  name: hive-config
  namespace: hive-metastore
data:
  hive-site.xml: |
    <configuration>
        <property>
            <name>javax.jdo.option.ConnectionURL
            </name>
            <value>{{ .Values.database.jdbcUrl }}</value>
        </property>
        <property>
            <name>javax.jdo.option.ConnectionDriverName</name>
            <value>{{ .Values.database.jdbcDriver }}</value>
        </property>
        <property>
            <name>javax.jdo.option.ConnectionUserName
            </name>
            <value>{{ .Values.database.user }}</value>
        </property>
        <property>
            <name>javax.jdo.option.ConnectionPassword</name>
            <value>{{ .Values.database.password }}</value>
        </property>

        <property>
            <name>hive.metastore.warehouse.dir</name>
            <value>{{ .Values.metastore.warehouseDir }}</value>
        </property>

        <property>
            <name>fs.s3a.endpoint</name>
            <value>{{ .Values.s3.endpoint }}</value>
        </property>
        <property>
            <name>fs.s3a.access.key
            </name>
            <value>{{ .Values.s3.accessKey }}</value>
        </property>
        <property>
            <name>fs.s3a.secret.key
            </name>
            <value>{{ .Values.s3.secretKey }}</value>
        </property>
        <property>
            <name>fs.s3a.path.style.access</name>
            <value>{{ .Values.s3.pathStyleAccess }}</value>
        </property>
        <property>
            <name>fs.s3a.impl
            </name>
            <value>org.apache.hadoop.fs.s3a.S3AFileSystem</value>
        </property>
    </configuration>
