apiVersion: apps/v1
kind: Deployment
metadata:
  name: starburst-hms
  namespace: hive-metastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starburst-hms
  template:
    metadata:
      labels:
        app: starburst-hms
    spec:
      containers:
        - name: hms
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 9083
          envFrom:
            - secretRef:
                name: hms-secret
          volumeMounts:
            - name: hive-config
              mountPath: /opt/hive/conf

      volumes:
        - name: hive-config
          configMap:
            name: hive-config