apiVersion: v1
kind: Secret
metadata:
  name: hms-secret
  namespace: hive-metastore
type: Opaque
stringData:
  HIVE_METASTORE_JDBC_URL: {{ .Values.database.jdbcUrl | quote }}
  HIVE_METASTORE_DRIVER: {{ .Values.database.jdbcDriver | quote }}
  HIVE_METASTORE_USER: {{ .Values.database.user | quote }}
  HIVE_METASTORE_PASSWORD: {{ .Values.database.password | quote }}

  S3_ACCESS_KEY: {{ .Values.s3.accessKey | quote }}
  S3_SECRET_KEY: {{ .Values.s3.secretKey | quote }}
  S3_ENDPOINT: {{ .Values.s3.endpoint | quote }}
  S3_PATH_STYLE_ACCESS: {{ .Values.s3.pathStyleAccess | quote }}
  REGION: {{ .Values.s3.region | quote }}

  GOOGLE_CLOUD_KEY_FILE_PATH: ""
  AZURE_ADL_CLIENT_ID: ""
  AZURE_ADL_CREDENTIAL: ""
  AZURE_ADL_REFRESH_URL: ""
  AZURE_ABFS_STORAGE_ACCOUNT: ""
  AZURE_ABFS_ACCESS_KEY: ""
  AZURE_WASB_STORAGE_ACCOUNT: ""
  AZURE_ABFS_OAUTH: ""
  AZURE_ABFS_OAUTH_TOKEN_PROVIDER: ""
  AZURE_ABFS_OAUTH_CLIENT_ID: ""
  AZURE_ABFS_OAUTH_SECRET: ""
  AZURE_ABFS_OAUTH_ENDPOINT: ""
  AZURE_WASB_ACCESS_KEY: ""
  HIVE_METASTORE_USERS_IN_ADMIN_ROLE: "admin"