apiVersion: v1
kind: Service
metadata:
  name: starburst-hms
  namespace: hive-metastore
spec:
  type: ClusterIP
  ports:
    - name: thrift
      port: 9083
      targetPort: 9083
  selector:
    app: starburst-hms
