apiVersion: v1
kind: Secret
metadata:
  name: airflow-secret
  namespace: airflow
type: Opaque
stringData:
  AIRFLOW__WEBSERVER__ADMIN_USERNAME: "admin"
  AIRFLOW__WEBSERVER__ADMIN_PASSWORD: "password"

  postgres-user: "airflow"
  postgres-password: "airflow"
  postgres-db: "airflow"
