apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: database
type: Opaque
stringData:
  postgres-username: "ecommerce_user"
  postgres-password: "ecommerce_password"
  postgres-database: "ecommerce_db"
  debezium-username: "debezium_user"
  debezium-password: "debezium_password"