apiVersion: v1
kind: Service
metadata:
  name: {{ include "hive-metastore.fullname" . }}
  labels:
    app: {{ include "hive-metastore.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9083
      protocol: TCP
      name: thrift
  selector:
    app: {{ include "hive-metastore.name" . }}
