apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}-secret
  labels:
    {{ include "postgres.labels" . | nindent 4 }}
type: Opaque
data:
  superuser-password: {{ .Values.postgres.superuserPassword | b64enc | quote }}
  {{- range .Values.databases }}
  {{ .name }}-username: {{ .user | b64enc | quote }}
  {{ .name }}-password: {{ .password | b64enc | quote }}
  {{- end }}

