apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.name" . }}-headless
  labels:
    {{ include "kafka.labels" . | nindent 4 }}
    component: kafka
spec:
  clusterIP: None
  ports:
    - name: broker
      port: {{ .Values.kafka.service.ports.broker }}
      targetPort: {{ .Values.kafka.service.ports.broker }}
    - name: controller
      port: {{ .Values.kafka.service.ports.controller }}
      targetPort: {{ .Values.kafka.service.ports.controller }}
  selector:
    {{ include "kafka.selectorLabels" . | nindent 4 }}
    component: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.service.name" . }}
  labels:
    {{ include "kafka.labels" . | nindent 4 }}
    component: kafka
spec:
  type: {{ .Values.kafka.service.type }}
  ports:
    - name: broker
      port: {{ .Values.kafka.service.ports.broker }}
      targetPort: {{ .Values.kafka.service.ports.broker }}
  selector:
    {{ include "kafka.selectorLabels" . | nindent 4 }}
    component: kafka