apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: ecommerce-streaming
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  sparkVersion: "3.5.0"

  driver:
    image: "docker.io/library/spark-kafka:v3.0"
    cores: 1
    coreLimit: "1200m"
    memory: "1g"
    serviceAccount: spark-operator
    volumeMounts:
      # Giữ nguyên mount ConfigMap để có code Python
      - name: spark-job
        mountPath: /opt/spark/work-dir

  executor:
    image: "docker.io/library/spark-kafka:v3.0"
    cores: 1
    instances: 2
    memory: "1g"
    volumeMounts:
      - name: spark-job
        mountPath: /opt/spark/work-dir

  mainApplicationFile: local:///opt/spark/work-dir/ecommerce_stream.py

  volumes:
    - name: spark-job
      configMap:
        name: spark-ecommerce-job