apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: ecommerce-streaming
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "docker.io/library/spark:v3.1"
  sparkVersion: "3.5.1"
  mainClass: "com.example.streaming.STREAMING"
  mainApplicationFile: "local:///opt/spark/jars/app.jar"

  restartPolicy:
    type: Always
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20

  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "1g"
    serviceAccount: spark-operator
    env:
      - name: ENV_JOB_RUN
        value: "prod"


  executor:
    cores: 1
    instances: 2
    memory: "1g"
    env:
      - name: ENV_JOB_RUN
        value: "prod"


