apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "airflow.name" . }}-config
  labels:
    {{ include "airflow.labels" . | nindent 4 }}
data:
  airflow.cfg: |
    [core]
    dags_folder = /opt/airflow/dags
    base_log_folder = /opt/airflow/logs
    executor = {{ .Values.airflow.config.core.executor }}
    parallelism = {{ .Values.airflow.config.core.parallelism }}
    dag_concurrency = {{ .Values.airflow.config.core.dagConcurrency }}
    max_active_runs_per_dag = {{ .Values.airflow.config.core.maxActiveRunsPerDag }}
    load_examples = {{ .Values.airflow.config.core.loadExamples }}
    sql_alchemy_conn = {{ include "airflow.database.url" . | quote }}
    default_timezone = {{ .Values.airflow.config.core.defaultTimezone | quote }}
    
    [webserver]
    base_url = http://localhost:8080
    default_ui_timezone = {{ .Values.airflow.config.webserver.defaultUiTimezone | quote }}
    expose_config = {{ .Values.airflow.config.webserver.exposeConfig }}
    enable_proxy_fix = {{ .Values.airflow.config.webserver.enableProxyFix }}
    
    [logging]
    logging_level = {{ .Values.airflow.config.logging.loggingLevel }}
    fab_logging_level = {{ .Values.airflow.config.logging.fabLoggingLevel }}
    
    [api]
    auth_backend = {{ .Values.airflow.config.api.authBackend }}


