{{- if .Values.airflow.dags.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "airflow.name" . }}-dags
  labels:
    {{ include "airflow.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  {{- if .Values.airflow.dags.persistence.storageClass }}
  storageClassName: {{ .Values.airflow.dags.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.airflow.dags.persistence.size }}
{{- end }}



