apiVersion: v1
kind: Secret
metadata:
  name: {{ include "airflow.name" . }}-secret
  labels:
    {{ include "airflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  fernet-key: {{ .Values.airflow.config.core.fernetKey | quote }}
  database-url: {{ include "airflow.database.url" . | quote }}
  postgres-password: {{ .Values.postgres.password | quote }}
  postgres-user: {{ .Values.postgres.user | quote }}
  postgres-db: {{ .Values.postgres.database | quote }}

