apiVersion: v1
kind: Service
metadata:
  name: {{ include "airflow.name" . }}-webserver
  labels:
    {{ include "airflow.labels" . | nindent 4 }}
    component: webserver
spec:
  type: {{ .Values.airflow.service.type }}
  ports:
    - port: {{ .Values.airflow.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{ include "airflow.selectorLabels" . | nindent 4 }}
    component: webserver


