apiVersion: v2
name: ecommerce-behavior-analysis
description: Ecommerce Behavior Analysis
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: postgres
    version: 0.1.0
    repository: "file://./charts/postgres"
  - name: airflow
    version: 0.1.0
    repository: "file://./charts/airflow"
  - name: superset
    version: 0.1.0
    repository: "file://./charts/superset"
  - name: trino
    version: 0.1.0
    repository: "file://./charts/trino"
  - name: kafka
    version: 0.1.0
    repository: "file://./charts/kafka"
  - name: clickhouse
    version: 0.1.0
    repository: "file://./charts/clickhouse"
  - name: hdfs
    version: 0.1.0
    repository: "file://./charts/hdfs"