replicaCount: 1

image:
  repository: my-hive-metastore
  tag: "4.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9083

postgres:
  host: postgres-metastore
  port: 5432
  db: metastore
  user: hive
  password: hivepassword

hdfs:
  namenode: hadoop-namenode
  port: 9000
  warehouseDir: hdfs://hadoop-namenode:9000/user/hive/warehouse

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi
