apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "spark-cluster.fullname" . }}-worker
  labels:
    {{ include "spark-cluster.labels" . | nindent 4 }}
    component: worker
spec:
  serviceName: {{ include "spark-cluster.fullname" .}}-worker-headless
  replicas: {{ .Values.spark.worker.replicas }}
  selector:
    matchLabels:
      {{ include "spark-cluster.selectorLabels" . | nindent 6 }}
      component: worker
  template:
    metadata:
      labels:
        {{ include "spark-cluster.selectorLabels" . | nindent 8 }}
        component: worker
    spec:
      containers:
        - name: spark-worker
          image: "{{ .Values.spark.worker.image.repository }}:{{ .Values.spark.worker.image.tag }}"
          imagePullPolicy: {{ .Values.spark.worker.image.pullPolicy }}
          command:
            - /opt/spark/bin/spark-class
            - org.apache.spark.deploy.worker.Worker
            - "spark://{{ include "spark-cluster.fullname" . }}-master: {{ .Values.spark.master.ports.cluster }}""
          ports:
            - name: web
              containerPort: {{ .Values.spark.worker.ports.web }}
              protocol: TCP
          env:
            {{- range .Values.spark.worker.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
                  {{- end }}
          resources:
            {{ toYaml .Values.spark.worker.resources | nindent 10 }}
          volumeMounts:
            - name: spark-worker-storage
              mountPath: /opt/spark/work-dir