image:
  repository: starburstdata/hive
  tag: "3.1.2-e.18"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9083

database:
  host: hms-postgres-postgresql.hive-metastore.svc.cluster.local
  port: 5432
  name: metastore
  user: hms-user
  password: hms-password
  jdbcDriver: org.postgresql.Driver
  jdbcUrl: jdbc:postgresql://hms-postgres-postgresql.hive-metastore.svc.cluster.local:5432/metastore

s3:
  enabled: true
  endpoint: http://minio-hl.minio.svc.cluster.local:9000
  accessKey: admin
  secretKey: password
  bucket: warehouse
  region: us-east-1
  pathStyleAccess: true

metastore:
  warehouseDir: s3a://warehouse/hive
  extraHiveConfig: { }
