apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.hive-metastore.fullname" . }}
  labels:
    app: {{ include "postgres.hive-metastore.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: {{ include "postgres.hive-metastore.name" . }}
